contrib: gpg-error: Fix the WCHAR patch to use the right *cpy function
This fixes build errors with current Clang versions, due to the
mismatched pointers with strcpy.

The previous form of this patch errored out like this:

    ../../src/estream.c:5104:11: error: incompatible pointer
     types passing 'WCHAR *' (aka 'unsigned short *') to parameter of type 'char *' [-Wincompatible-pointer-types]
     5104 |   strcpy (p, "_estream");
          |           ^
    /opt/llvm-mingw/aarch64-w64-mingw32/include/string.h:61:45: note:
     passing argument to parameter '_Dest' here
       61 |   char * __cdecl strcpy(char * __restrict__ _Dest,const char * __restrict__ _Source);
          |                                             ^

(cherry picked from commit 3f0a3546730d5fa97aa257200954a5f0c117a797)
Signed-off-by: Steve Lhomme <robux4@ycbcr.xyz>